export const QUERY_KEYS = {
  USER_ID: 'USER_ID',
  USER_EMAIL: 'USER_EMAIL',

  INTERESTS: 'INTERESTS',

  ACTIVITIES: 'ACTIVITIES',
  ACTIVITIES_INACTIVE: 'ACTIVITIES_INACTIVE',
  ACTIVITIES_BY_TYPE: 'ACTIVITIES_BY_TYPE',
  ACTIVITY_ID: 'ACTIVITY_ID',

  ATTENDANCES: 'ATTENDANCES',

  NOTIFICATIONS_BY_USER: 'NOTIFICATIONS_BY_USER',
}
